/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pencairan.kredit.nasabah;

/**
 *
 * @author BIMO
 */
public class Form_Master extends javax.swing.JFrame {

    /**
     * Creates new form FormMaster
     */
    public Form_Master() {
        initComponents();
        setTitle("Form Master");
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(this);
        
        setTanggal();
    }
    
    private void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("d MMMM yyyy");
        lblTanggal.setText(kal.format(sekarang));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_app = new javax.swing.JLabel();
        lbl_penentuan = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Data_Nasabah = new javax.swing.JMenu();
        Menu_Input_Data = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Menu_Logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_app.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_app.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_app.setText("APLIKASI");
        lbl_app.setAlignmentX(50.0F);
        lbl_app.setAlignmentY(50.0F);
        lbl_app.setFocusCycleRoot(true);
        lbl_app.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_penentuan.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_penentuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_penentuan.setText("PENENTUAN PENCAIRAN KREDIT NASABAH");

        lblTanggal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTanggal.setText("jLabel3");

        Menu_Data_Nasabah.setText("Input Nasabah");
        Menu_Data_Nasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Data_NasabahMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Data_Nasabah);

        Menu_Input_Data.setText("Input Nilai");
        Menu_Input_Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_Input_DataMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Input_Data);

        jMenu1.setText("Ranking");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("About");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        Menu_Logout.setText("Logout");
        Menu_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_LogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTanggal)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lbl_penentuan)
                .addGap(0, 164, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(521, 521, 521)
                .addComponent(lbl_app)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTanggal)
                .addGap(161, 161, 161)
                .addComponent(lbl_app, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_penentuan)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Data_NasabahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Data_NasabahMouseClicked
        //pindah ke form nasabah
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Input_Nasabah().setVisible(true);
            }
        });
    }//GEN-LAST:event_Menu_Data_NasabahMouseClicked

    private void Menu_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_LogoutMouseClicked
        //Logout
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }//GEN-LAST:event_Menu_LogoutMouseClicked

    private void Menu_Input_DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_Input_DataMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Input_Nilai().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_Menu_Input_DataMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Perankingan().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_About().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu_Data_Nasabah;
    private javax.swing.JMenu Menu_Input_Data;
    private javax.swing.JMenu Menu_Logout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lbl_app;
    private javax.swing.JLabel lbl_penentuan;
    // End of variables declaration//GEN-END:variables
}
