/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pencairan.kredit.nasabah;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Bimo
 */
public class tabel_cari extends javax.swing.JDialog {

    /**
     * Creates new form tabel_Cari
     */
    
    String TBL;
    String a, b, c;
    String[] strJudul = {"Kode Nasabah", "Nama", "Kredit Yang Diambil"};
    DefaultTableModel tabMode;
    
    public tabel_cari(Component c, String s) {
        super(new JDialog(), "Tabel " + s, true);
        initComponents();
        setTitle("Tabel Cari");
        this.setLocationRelativeTo(null);
    
            //membuat tabel tidak bisa diedit saat di klik
        tabMode = new DefaultTableModel(null,strJudul){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
              return false;
            }
        };
    
	table.setModel(tabMode);
        table.addMouseListener(new MouseAdapter()
        {
            public void mouseClicked(MouseEvent mouseEvent)
             {
                 jBPilih.setEnabled(true);
                    
             }
        });
        
        TBL = s;
        if (s.equals("Nasabah")) {
            tabelDataNasabah();
        }
        
        jBPilih.setEnabled(false);
    }
    
    void tampilDataNasabah()
 	 {
 	 	int baris = table.getSelectedRow();
                a = table.getValueAt(table.getSelectedRow(), 0).toString();
                b = table.getValueAt(table.getSelectedRow(), 1).toString();
                c = table.getValueAt(table.getSelectedRow(), 2).toString();
 	 }
    
    void hapusTabel(){
        int brs = tabMode.getRowCount();
        for(int i=0;i<brs;i++){
            tabMode.removeRow(0);
        }
    }   
                       
    
    private void tabelDataNasabah() {
        try {

            Koneksi Objkoneksi = new Koneksi();
            Connection con = Objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String sql = "Select * from nasabah ORDER BY Duit_kredit ASC";

            ResultSet rs = st.executeQuery(sql);
            hapusTabel();
            while (rs.next()) {
                String kode = rs.getString("Kode_Nasabah");
                String nama = rs.getString("Nama");
                String duit = rs.getString("Duit_kredit");
                String[] data = {kode,nama,duit};
                tabMode.addRow(data);
            }
            st.close();
            rs.close();
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jBPilih = new javax.swing.JButton();
        jBBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jBPilih.setText("Pilih");
        jBPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPilihActionPerformed(evt);
            }
        });

        jBBatal.setText("Batal");
        jBBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addComponent(jBPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBatal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPilihActionPerformed
        // TODO add your handling code here:
        tampilDataNasabah();
        dispose();
    }//GEN-LAST:event_jBPilihActionPerformed
    
    private void jBBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBBatalActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBatal;
    private javax.swing.JButton jBPilih;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
